############################################################################
# Contest 2026 team 039 VelaBridge app - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = velabridge_app
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_039_VELABRIDGE_APP)

MAINSRC = velabridge_app_main.c

include $(APPDIR)/Application.mk

